[package]
name = "installer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.29"
octocrab = "0.49.5"
reqwest = "0.13.1"
simple_logger = "5.1.0"
tokio = "1.48.0"
web-view = { git = "https://github.com/Airyzz/web-view" }
rustls = { version = "0.23", default-features = false, features = [
    "aws-lc-rs",
] }
urlencoding = "2.1.3"
platform-dirs = "0.3.0"
zip = "7.0.0"
pgp = "0.18.0"
clap = { version = "4.5.53", features = ["derive"] }
rfd = "0.16.0"
rand = "0.8.5"
shortcuts-rs = "1.1.1"
sysinfo = "0.37.2"

[build-dependencies]
winresource = "0.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
panic = "abort"
strip = true
